#!/usr/bin/env python

import sys
import os
import random

letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
llen=len(letters)

def main():
    if len(sys.argv) > 1:
        l=int(sys.argv[1])
    else:
        l=40

    pw=""
    oc=""

    for i in range(l):
        done=False
        while not done:
            for z in range(random.randrange(73,237)):
                c=random.randrange(llen)
            if pw=="" or (len(pw)>0 and letters[c]!=oc):
                done=True
        oc=letters[c]

        pw+=oc

    print('{ "Authentication":"'+pw+'" }')

if __name__ == "__main__":
    main()

