#!/bin/bash
pip3=`which pip3`
OFS=`stat --printf="%s" install`

BaseDir="/home/JackrabbitRelay2"

cd /home/GitHub/JackrabbitRelay

mkdir -p $BaseDir > /dev/null 2>&1
mkdir -p $BaseDir/Config > /dev/null 2>&1
for d in Base Data Extras Logs Ledger Statistics/Balances Statistics/Charts ; do
    mkdir -p $BaseDir/$d > /dev/null 2>&1

    cp -r /home/GitHub/JackrabbitRelay/$d/* $BaseDir/$d
done

if [ x$1 != 'xnopull' ] ; then
    for i in `cat requirements.txt` ; do
        $pip3 install -U $i
    done

    for i in $BaseDir/Data/*.symbolmap ; do 
        N=`echo $i | cut -d/ -f5 | cut -d. -f1`
        $BaseDir/Extras/TV2Exchange $N
    done
fi

git pull https://github.com/rapmd73/JackrabbitRelay

NFS=`stat --printf="%s" install`

if [ "$NFS" != "$OFS" ] ; then
    echo Running update again...
    /home/GitHub/JackrabbitRelay/install nopull
fi
