#!/bin/bash

# Crontab entry ( without has mark #
# @reboot ( /home/JackrabbitRelay/Base/RelayLauncher & ) > /dev/null 2>&1

BaseDir="/home/JackrabbitRelay2/Base"
GitHubBase="/home/GitHub/JackrabbitRelay/Base"

if [ -z $1 ] ; then
    echo At least one exchange name to use must be given.
    exit 1
fi

cd $BaseDir

fnSpot="CCXT-PlaceOrder.spot"
fnFuture="CCXT-PlaceOrder.future"

echo Updating / replacing PlaceOrder OANDA
cp $GitHubBase"/OANDA-PlaceOrder" $BaseDir"/PlaceOrder.oanda"

echo Updating / replacing PlaceOrder Tester
cp $GitHubBase"/TESTER-PlaceOrder" $BaseDir"/PlaceOrder.tester"

echo Updating / replacing PlaceOrder spot
cp $GitHubBase"/"$fnSpot $BaseDir"/"$snSpot

echo Updating / replacing PlaceOrder future
cp $GitHubBase"/"$fnFuture $BaseDir"/"$fnFuture

for i in $@ ; do
    exchange=$1
    echo Updating / replacing PlaceOrder.$exchange spot/future
    cp $GitHubBase"/"$fnSpot PlaceOrder.$exchange.spot
    cp $GitHubBase"/"$fnFuture PlaceOrder.$exchange.future
    shift
done
