#!/bin/bash
pip3=`which pip3`
OFS=`stat --printf="%s" update`

cd /home/GitHub/JackrabbitRelay

if [ x$1 != 'xnopull' ] ; then
    for i in `cat requirements.txt` ; do
        $pip3 install -U $i
    done

    for i in /home/JackrabbitRelay/Data/*.symbolmap ; do 
        N=`echo $i | cut -d/ -f5 | cut -d. -f1`
        /home/JackrabbitRelay/Extras/TV2Exchange $N
    done

fi

#git pull https://github.com/rapmd73/JackrabbitRelay

mkdir -p /home/JackrabbitRelay > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Base > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Config > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Data > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Sandbox > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Logs > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Ledger > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Statistics/Balances > /dev/null 2>&1
mkdir -p /home/JackrabbitRelay/Statistics/Charts > /dev/null 2>&1

cp -r /home/GitHub/JackrabbitRelay/Base/* /home/JackrabbitRelay/Base
cp -r /home/GitHub/JackrabbitRelay/Extras/* /home/JackrabbitRelay/Extras

if test -f /home/Equilibrium/install ; then
    /home/GitHub/JackrabbitRelay/Extras/Equilibrium/install
fi

if test -f /home/Procurator/install ; then
    /home/GitHub/JackrabbitRelay/Extras/Procurator/install
fi

if test -f /home/BlackCrowHunter/install ; then
    /home/GitHub/JackrabbitRelay/Extras/BlackCrowHunter/install
fi

NFS=`stat --printf="%s" update`

if [ "$NFS" != "$OFS" ] ; then
    echo Running update again...
    /home/GitHub/JackrabbitRelay/update nopull
fi
