#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import time
import json

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

###
### Main code base.
###

cfiles=os.listdir(JRRconfig.LedgerDirectory)

for cf in cfiles:
    if cf.find('.ledger')>-1:
        en=cf.split('.')[0]
        ac=cf.split('.')[1]

        print("Checking",en,ac)

        cmd=JRRconfig.StatisticsDirectory+'/ChartLedger '+en+' '+ac
        os.system(cmd)
