#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import time
import datetime
import json
import plotly.express as px

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

###
### Main code base. 
###

if len(sys.argv) > 4:
    en=sys.argv[1]
    sa=sys.argv[2]
    asset=sys.argv[3].upper()
    bf=sys.argv[4]
else:
    print("An exchange, a (sub)account, an asset, and a balance file must be provided.")
    sys.exit(1)

xps=[]
bal=[]

fh=open(bf,'r')
while True:
    line=fh.readline().strip()
    if not line:
        break
    Balance=json.loads(line);

    if asset in Balance:
        bal.append(float(Balance[asset]))
    else:
        bal.append(0)

    t=float(Balance['DateTime'])
    timestamp=datetime.datetime.fromtimestamp(t)
    dt=timestamp.strftime('%Y-%m-%d')

    xps.append(dt)
fh.close()

p=asset.replace(':','').replace('-','').replace('/','')
fn=JRRconfig.ChartsDirectory+'/'+en+'.'+sa+'.'+p+'.html'
ts=en.upper()+' ('+sa+'): '+asset.lower()
fig=px.line(x=xps,y=bal)
fig.update_layout(xaxis_title="Date",yaxis_title="Balance")
fig.update_layout(title={"text":ts,"x":0.5,"xanchor":"center","yanchor":"top"})
fig.write_html(fn)

