#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import time
import json

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

###
### Main code base.
###

cfiles=os.listdir(JRRconfig.BalancesDirectory)

for cf in cfiles:
    if cf.find('.balances')>-1:
        en=cf.split('.')[0]
        ac=cf.split('.')[1]
        fn=JRRconfig.BalancesDirectory+'/'+en+'.'+ac+'.balances'

        print('Checking',en,ac)

        cl=[]
        fh=open(fn,'r')
        while True:
            line=fh.readline().strip()
            if not line:
                break
            Balance=json.loads(line);

            for asset in Balance:
                if asset not in cl and asset.lower()!='datetime':
                    cl.append(asset)
        fh.close()

        for asset in cl:
            cmd=JRRconfig.StatisticsDirectory+'/ChartBalances '+en+' '+ac+' "'+asset+'" '+fn
            os.system(cmd)
            cmd=JRRconfig.StatisticsDirectory+'/ChartTransactions '+en+' '+ac+' "'+asset+'"'
            os.system(cmd)

