#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import time
import json

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

def ReadConfigFile(cfg):
    keys=[]

    fn=JRRconfig.ConfigDirectory+'/'+cfg
    cf=open(fn,'rt+')
    for line in cf.readlines():
        if len(line.strip())>0 and line[0]!='#':
            try:
                key=json.loads(line)
            except:
                JRRlog.ErrorLog("Reading Configuration",'damaged: '+line)

            found=False
            for k in keys:
                if key['Account']==k['Account']:
                    found=True

            if not found:
                keys.append(key)
    cf.close()

    return keys

###
### Main code base. 
###

cfiles=os.listdir(JRRconfig.ConfigDirectory)

for cf in cfiles:
    if cf.find('.cfg')>-1:
        # Skip the identity file
        if cf=='Identity.cfg':
            continue
        keys=ReadConfigFile(cf)

        en=cf.split('.')[0]
        for Active in keys:
            ac=Active['Account']

            fn=JRRconfig.BalancesDirectory+'/'+en+'.'+ac+'.balances'
            cmd=JRRconfig.StatisticsDirectory+'/Balances '+en+' '+ac+' log '+fn
            print('Checking',en,ac)
            os.system(cmd)

