#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit BlackCrowHunter
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import time
import datetime
import json
import plotly.express as px

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

if len(sys.argv) > 2:
    en=sys.argv[1]
    acct=sys.argv[2]
else:
    print("An exchange and account must be provided.")
    sys.exit(1)

fn=JRRconfig.LedgerDirectory+'/'+en+'.'+acct+'.ledger'
if not os.path.exists(fn):
    print(fn)
    print(en,acct,"ledger not found")
    sys.exit(1)

xps=[]
run=[]

bal=0.0
counter=0

fh=open(fn,'r')
while True:
    line=fh.readline().strip()

    if not line:
        break

    data=json.loads(line)

    dt=data['DateTime']
    direction=data['Action'].lower()

    st=data['Exchange'].lower()+'STATUS'
    status=data[st].lower()
    if status!='closed':
        continue

    if direction!='buy' and direction!='sell':
        continue

    cs=data['Exchange'].lower()+'COST'
    if data[cs]==None:
        continue
    close=float(data[cs])

    if direction=='buy':
        bal-=(close)
    if direction=='sell':
        bal+=(close)

    xps.append(dt)
    run.append(bal)
    counter+=1

fh.close()

if counter==0:
    print('No data')
    sys.exit(1)

fn=JRRconfig.ChartsDirectory+'/'+en+'.'+acct+'.Ledger.html'
fig=px.line(x=xps,y=run)
fig.update_layout(xaxis_title="Date/Time",yaxis_title="Profit/Loss")
fig.update_layout(title={"text":en.capitalize()+" "+acct+" Ledger","x":0.5,"xanchor":"center","yanchor":"top"})
fig.write_html(fn)

