#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# OANDA example unbounded grid bot.

# This is a very simple grid bot using unbounded grids.

# For demonstration purposes only.
# FREE VERSION, NOT SUPPORTED BEYOUND SCOPE OF Jackrabbit Relay.
# See aponsored version.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import gc
import json
import time
import datetime

import JackrabbitRelay as JRR
import JRRsupport

# Slash (/) at end is required

oandaBotTickerData='/home/Oanda/TickerData/'

# Initialize global signal interceptor. prevent file trashing on CTRL-C

interceptor=JRRsupport.SignalInterceptor()

# Forex sessions:
#
# Tokyo     00:00 to 09:00  T
# London    08:00 to 17:00  L
# New York  13:00 to 22:00  N
# Sydney    20:00 to 05:00  S

# Get forex session

def GetForexSession():
    cs=''
    hour=time.localtime().tm_hour
    if hour>=0 and hour<=9:
        cs+='T'
    if hour>=8 and hour<=17:
        cs+='L'
    if hour>=13 and hour<=22:
        cs+='N'
    if hour>=20 or hour<=5:
        cs+='S'
    return(cs)

# Send the order to Relay

def SendOrder(relay,**kwargs):
    Order={}
    Order['Identity']=relay.Identity['Identity']
    Order['Exchange']=relay.GetExchange()
    Order['Account']=relay.GetAccount()
    Order['Asset']=relay.GetAsset()
    Order['OrderType']="market"
    Order['Action']=kwargs.get('Action')

    if 'Units' in kwargs:
        Order['Units']=str(kwargs.get('Units'))
    if 'Ticket' in kwargs:
        Order['Ticket']=kwargs.get('Ticket')

    result=relay.SendWebhook(Order)
    return result

# Get the order ID. If there isn't an ID, the order FAILED.

def GetOrderID(res):
    if res.find('Order Confirmation ID')>-1:
        s=res.find('ID:')+4
        for e in range(s,len(res)):
            if res[e]=='\n':
                break
        oid=res[s:e]

        return oid
    return None

# These functions are needed to load each ticker file set into the Config as each pair is loaded. This is done
# to prevent multiple loads os the same data.

# Load ticker data

def LoadTickerData(Config,ticker):
    TickerList=[]
    fn=oandaBotTickerData+Config['Account']+'.'+Config['Asset'].replace('/','')+'.ticker'
    if os.path.exists(fn)==True:
        lines=JRRsupport.ReadFile(fn).split('\n')
        for line in lines:
            line=line.strip()
            if line=='':
                continue
            try:
                td=json.loads(line)
                TickerList.append(td)
            except: # damaged, skip
                pass

    Config['TickerData']=TickerList[-86400:]

    # Only update if the current ticker is different then the previous
    if len(Config['TickerData'])>1:
        if ticker['Bid']!=Config['TickerData'][-1]['Bid'] \
        and ticker['Ask']!=Config['TickerData'][-1]['Ask']:
            Config['TickerData'].append(ticker)
            # Do the math here only ONCE. Will be used multiple times.
            Config['TickerData'][-1]['LenBA']=len(TickerList)
            if Config['Direction'].lower()=='long':
                Config['TickerData'][-1]['SumBA']=sum(item['Bid'] for item in TickerList)
                Config['TickerData'][-1]['MaxBA']=max(item['Bid'] for item in TickerList)
                Config['TickerData'][-1]['MinBA']=min(item['Bid'] for item in TickerList)
            else:
                Config['TickerData'][-1]['SumBA']=sum(item['Ask'] for item in TickerList)
                Config['TickerData'][-1]['MaxBA']=max(item['Ask'] for item in TickerList)
                Config['TickerData'][-1]['MinBA']=min(item['Ask'] for item in TickerList)

            SaveTickerData(Config)
    else:
        Config['TickerData'].append(ticker)
        # Do the math here only ONCE. Will be used multiple times.
        Config['TickerData'][0]['LenBA']=len(TickerList)
        if Config['Direction'].lower()=='long':
            Config['TickerData'][0]['SumBA']=sum(item['Bid'] for item in TickerList)
            Config['TickerData'][0]['MaxBA']=max(item['Bid'] for item in TickerList)
            Config['TickerData'][0]['MinBA']=min(item['Bid'] for item in TickerList)
        else:
            Config['TickerData'][0]['SumBA']=sum(item['Ask'] for item in TickerList)
            Config['TickerData'][0]['MaxBA']=max(item['Ask'] for item in TickerList)
            Config['TickerData'][0]['MinBA']=min(item['Ask'] for item in TickerList)
        SaveTickerData(Config)

    Config['TickerData']=Config['TickerData'][-86400:]

    return Config

# Save ticker data

def SaveTickerData(Config):
    interceptor.Critical(True)
    TickerList=Config['TickerData']
    fn=oandaBotTickerData+Config['Account']+'.'+Config['Asset'].replace('/','')+'.ticker'
    fh=open(fn,"w")
    for ticker in TickerList:
        fh.write(json.dumps(ticker)+'\n')
    fh.close()
    interceptor.Critical(False)

    interceptor.SafeExit()

# Find the closest rime number to the one provided

def isPrime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True

def ClosestPrime(n):
    if n<=2:
        return 2
    if isPrime(n):
        if n>2:
            n-=1
            while not isPrime(n):
                n-=1
        return n
    if n%2==0:
        n-=1
    while not isPrime(n):
        n-=2
    return n

# Get orderbook direction or pressure

def GetOrderBookDirection(relay,Config):
    orderbook=relay.GetOrderBook(symbol=Config['Asset'])
    lob=len(orderbook)
    if lob==0:
        return "closed"

    m=lob/2
    h=m+(m/2)
    l=m-(m/2)

    long=0
    short=0

    for idx in range(int(l),int(h)):
        cur=orderbook[idx]
        price=round(float(cur['price']),4)
        long+=(float(cur['longCountPercent']))
        short+=(float(cur['shortCountPercent']))

    total=long+short
    tl=(long/total)*100
    ts=(short/total)*100

    confirmation=abs(tl-ts)
    if tl>=ts:
        Config['obDirection']='long'
    else:
        Config['obDirection']='short'

    return Config

# Predict price consolidation

def PredictConsolidatedPrice(relay,Config):
    TickerList=Config['TickerData']

    # Main algorithm

    if 'LenBA' not in TickerList:
        n=len(TickerList)
    else:
        n=TickerList['LenBA']
    if n==0:
        return 0,0

    if 'SumBA' not in TickerList:
        sum_of_prices=0
        if Config['Direction'].lower()=='long':
            sum_of_prices=sum(item['Bid'] for item in TickerList)
        else:
            sum_of_prices=sum(item['Ask'] for item in TickerList)
    else:
        sum_of_prices=TickerList['SumBA']

    mean=sum_of_prices/n

    sum_of_squared_differences=0
    for price in TickerList:
        if Config['Direction'].lower()=='long':
            sum_of_squared_differences+=(price['Bid']-mean)**2
        else:
            sum_of_squared_differences+=(price['Ask']-mean)**2
    standard_deviation=(sum_of_squared_differences/n)**0.5

    predicted_price=mean
    confidence=100*(1-standard_deviation/mean)

    # Set the minimum and rate the % appropriately
    if n<14400:
        f=n/14400
        confidence*=f

    return predicted_price,confidence

# Calculate additive pip profits based upon ticker spread

def CalculatePipProfits(relay,Config):
    TickerList=Config['TickerData']

    if 'LenBA' not in TickerList:
        n=len(TickerList)
    else:
        n=TickerList['LenBA']

    if n<2:
        return 0

    spread = []
    for price in TickerList:
        spread.append(price['Spread'])

    return round(sum(spread)/len(spread),5)

# Calculate volatility in pips

def CalculateVolatilityPips(relay,Config):
    TickerList=Config['TickerData']

    if 'LenBA' not in TickerList:
        n=len(TickerList)
    else:
        n=TickerList['LenBA']

    if n>1:
        if 'SumBA' not in TickerList:
            if Config['Direction'].lower()=='long':
                s=sum(item['Bid'] for item in TickerList)

                mean=s/n

                deviations=[]
                for price in TickerList:
                    deviations.append((price['Bid']-mean)**2)
            else:
                s=sum(item['Ask'] for item in TickerList)

                mean=s/n

                deviations=[]
                for price in TickerList:
                    deviations.append((price['Ask']-mean)**2)
        else:
            s=TickerList['SumBA']
            mean=s/n
            if Config['Direction'].lower()=='long':
                deviations=[]
                for price in TickerList:
                    deviations.append((price['Bid']-mean)**2)
            else:
                deviations=[]
                for price in TickerList:
                    deviations.append((price['Ask']-mean)**2)

        variance=sum(deviations)/len(deviations)
        std_dev=variance**0.5

        return round(((std_dev/mean)*100)*0.001,5)
    return 0

# Read the configuration file

def ReadConfig(fname):
    required=[ "Account","Asset","PipProfit","MarginPips","UnitPips","UnitStart","UnitStep","MarginLimit", \
               "Direction","Clustering","ClusterStyle","Confidence","Confirmation","Volatility" ]

    Config={}
    lines=JRRsupport.ReadFile(fname).split('\n')
    for line in lines:
        line=line.strip()
        if line==None or line=='' or line[0]=='#':
            continue
        try:
            cfg=json.loads(line)
        except:
            print(f'Config line damaged: {line}')
            sys.exit(1)

        # Set safe defaults

        if 'MarginPips' not in cfg:
            cfg['MarginPips']="Yes"
        if 'UnitPips' not in cfg:
            cfg['UnitPips']="Yes"
        if 'Clustering' not in cfg:
            cfg['Clustering']="No"
        if 'ClusterStyle' not in cfg:
            cfg['ClusterStyle']="Defensive"
        if 'Confidence' not in cfg:
            cfg['Confidence']=99.73
        if 'Confirmation' not in cfg:
            cfg['Confirmation']="Yes"
        if 'Volatility' not in cfg:
            cfg['Volatility']="Yes"

        for item in required:
            if item not in cfg:
                print(f'Item "{item}" is missing from this line:')
                print(f'{line}')
                sys.exit(1)

        dn=cfg['Asset']+'.'+cfg['Account']
        Config[dn]=cfg

        if type(Config[dn]['Confidence']) is not float:
            Config[dn]['Confidence']=float(Config[dn]['Confidence'])

        Config[dn]['First']=True
        Config[dn]['BuyPips']=0
    return Config

# We don't want any order "over-stacking", unless Clustering is set to yes, so we
# verify that an order isn't within range of anothwer order. Its a lazy way of
# creating an "unbounded" grid.

def AlreadyBought(relay,asset,price,pipDistance):
    openTrades=relay.GetOpenTrades(symbol=asset)
    for trade in openTrades:
        roundedPrice=round(price,5)
        buyPrice=round(float(trade['price']),5)
        if roundedPrice>=(buyPrice-pipDistance) and roundedPrice<=(buyPrice+pipDistance):
            return True
    return False

# Apply some intelligence to the clustering functionality

def AllowClustering(relay,Config):
    if Config['Clustering'].lower()!='yes':
        return False

    if Config['marginLimit']<=30:
        return False

    price,confidence=PredictConsolidatedPrice(relay,Config)

    if Config['Confirmation'].lower()=='yes':
        dir=(Config['obDirection']==Config['Direction'].lower())
    else:
        dir=True

    ml=Config['marginLimit']*0.73
    if Config['marginUsed']<ml:
        if confidence>=Config['Confidence'] and dir==True:
            return True
    return False

# Determine the cluster style, defenseive or aggrssive

def ClusterStyle(openTrades,relay,pair,Config):
    if Config['ClusterStyle'].lower()=='aggressive':
        ml=Config['marginLimit']*0.73
        if Config['marginUsed']<ml:
            lotSize=HighestLotSize(openTrades,relay,pair,Config)
        else:
            lotSize=LowestLotSize(openTrades,relay,pair,Config)
    else:
        lotSize=LowestLotSize(openTrades,relay,pair,Config)

    return lotSize

# Find the lowest lot size used in the list of open trades. This is a good way to make
# the entire process dynamic and fluid as lot size can be varied by any metric,
# including but not limited to, the amount of margin used.

def LowestLotSize(openTrades,relay,asset,Config):
    # figure out the starting point and step size

    if Config['UnitStart'].lower()=='prime':
        lowestSize=ClosestPrime(int(Config['marginLimit']*0.2))
    else:
        lowestSize=int(Config['UnitStart'])

    if Config['UnitStep'].lower()=='prime':
        lotSize=ClosestPrime(int(lowestSize/2))
    else:
        lotSize=int(Config['UnitStep'])

    done=False
    while not done:
        found=False
        for trade in openTrades:
            units=abs(int(trade['currentUnits']))
            if lowestSize==units:
                found=True
                lowestSize=units+lotSize
        if not found:
            done=True

    return lowestSize

def HighestLotSize(openTrades,relay,asset,Config):
    # figure out the starting point and step size

    if Config['UnitStart'].lower()=='prime':
        highestSize=ClosestPrime(int(Config['marginLimit']*0.2))
    else:
        highestSize=int(Config['UnitStart'])

    if Config['UnitStep'].lower()=='prime':
        lotSize=ClosestPrime(int(highestSize/2))
    else:
        lotSize=int(Config['UnitStep'])

    for trade in openTrades:
        units=abs(int(trade['currentUnits']))
        if highestSize<=units:
            highestSize=units+lotSize

    return highestSize

# Get the margin used

def GetMarginUsed(relay,asset):
    marginUsed=0
    positions=relay.GetPositions()
    if positions!=None:
        for pos in positions:
            srch=pos['instrument'].replace('_','/')
            if srch==asset:
                marginUsed=round(float(pos['marginUsed']),5)
                break
    return marginUsed

# Manage Long positions

def ManageLongs(relay,pair,Config,ticker):
    # Get the margin used
    Config['marginUsed']=GetMarginUsed(relay,pair)

    # Get the list of open trades

    openTrades=relay.GetOpenTrades(symbol=pair)

    # Figure out orderbook direction

    Config['obDirection']=GetOrderBookDirection(relay,Config)

    isClustering=AllowClustering(relay,Config)
    if isClustering==True:
        clusterStr="Cluster "
    else:
        clusterStr=""

    lowestPrice=999999
    if len(openTrades)>0:
        for trade in openTrades:
            id=trade['id']
            iu=int(trade['currentUnits'])
            price=float(trade['price'])

            if price<(lowestPrice+Config['pipStep']+ticker['Spread']):
                lowestPrice=price;

            # CLOSE any position below profit level

            sellPrice=(price+Config['pipStep']+Config['BuyPips']+ticker['Spread'])
            if iu>0 and ticker['Bid']>=sellPrice:
                result=SendOrder(relay,Action="Close",Ticket=id)
                oid=GetOrderID(result)
                if oid!=None:
                    relay.JRLog.Write(f"{GetForexSession():4} {id} Long - {oid} Sell @{sellPrice:7.5f} -> {abs(iu)} {Config['balance']:8.5f}/{Config['marginUsed']:.5f}")
                    openTrades=relay.GetOpenTrades(symbol=pair)

                # Replaceent order, start at bottom

                if not AlreadyBought(relay,pair,ticker['Bid'],Config['pipStep']+Config['BuyPips']+Config['marginPips']+Config['unitPips']+Config['VolatilityPips']+ticker['Spread']) or isClustering:
                    # Get the margin used
                    Config['marginUsed']=GetMarginUsed(relay,pair)

                    lotSize=ClusterStyle(openTrades,relay,pair,Config)
                    newPos=Config['marginUsed']+(float(relay.Markets[pair]['marginRate'])*lotSize)

                    if Config['marginLimit']<0 or (Config['marginLimit']>0 and newPos<Config['marginLimit']):
                        details=relay.GetOrderDetails(OrderID=id)[-1]
                        price=float(details['price'])
                        result=SendOrder(relay,Action="buy",Units=lotSize)
                        oid=GetOrderID(result)
                        if oid!=None:
                            relay.JRLog.Write(f"{GetForexSession():4} Long - {clusterStr}Replacement {oid} Buy @{price:7.5f} -> {lotSize}")
                            openTrades=relay.GetOpenTrades(symbol=pair)
                            Config['BuyPips']=ticker['Spread']
    # No trades to scan
    elif Config['First']==True and (Config['marginLimit']<0 or Config['marginLimit']>0):
        lowestPrice=ticker['Bid']
        lotSize=LowestLotSize(openTrades,relay,pair,Config)
        buy=ticker['Bid']
        result=SendOrder(relay,Action="buy",Units=lotSize)
        oid=GetOrderID(result)
        if oid!=None:
            Config['BuyPips']=ticker['Spread']
            Config['First']=False
            relay.JRLog.Write(f"{GetForexSession():4} Long - {oid} Buy @{buy:7.5f} -> {lotSize}")
            openTrades=relay.GetOpenTrades(symbol=pair)

    # Next buy price minus pip step

    buy=round(lowestPrice-Config['pipStep']-Config['BuyPips']-Config['marginPips']-Config['unitPips']-Config['VolatilityPips']-ticker['Spread'],5)
    lotSize=LowestLotSize(openTrades,relay,pair,Config)

    if ticker['Bid']<buy:
        if not AlreadyBought(relay,pair,ticker['Bid'],Config['pipStep']+Config['BuyPips']+Config['marginPips']+Config['unitPips']+Config['VolatilityPips']+ticker['Spread']):
            lotSize=ClusterStyle(openTrades,relay,pair,Config)
            newPos=Config['marginUsed']+(float(relay.Markets[pair]['marginRate'])*lotSize)

            if Config['marginLimit']<0 or (Config['marginLimit']>0 and newPos<Config['marginLimit']):
                details=relay.GetOrderDetails(OrderID=id)[-1]
                price=float(details['price'])
                result=SendOrder(relay,Action="buy",Units=lotSize)
                oid=GetOrderID(result)
                if oid!=None:
                    relay.JRLog.Write(f"{GetForexSession():4} Long - {oid} Buy @{price:7.5f} -> {lotSize}")
                    Config['BuyPips']=ticker['Spread']
                    openTrades=relay.GetOpenTrades(symbol=pair)

    return Config

# Manage short positions

def ManageShorts(relay,pair,Config,ticker):
    # Get the margin used
    Config['marginUsed']=GetMarginUsed(relay,pair)

    openTrades=relay.GetOpenTrades(symbol=pair)

    # Figure out orderbook direction

    Config['obDirection']=GetOrderBookDirection(relay,Config)

    # Get the list of open trades

    isClustering=AllowClustering(relay,Config)
    if isClustering==True:
        clusterStr="Cluster "
    else:
        clusterStr=""

    highestPrice=0
    if len(openTrades)>0:
        for trade in openTrades:
            id=trade['id']
            iu=int(trade['currentUnits'])
            price=float(trade['price'])

            if price>(highestPrice+Config['pipStep']+ticker['Spread']):
                highestPrice=price;

            # CLOSE any position below profit level

            sellPrice=(price-Config['pipStep']-Config['BuyPips']-ticker['Spread'])
            if iu<0 and ticker['Ask']<=sellPrice:
                result=SendOrder(relay,Action="Close",Ticket=id)
                oid=GetOrderID(result)
                if oid!=None:
                    relay.JRLog.Write(f"{GetForexSession():4} {id} Short - {oid} Sell @{sellPrice:7.5f} -> {abs(iu)} {Config['balance']:8.5f}/{Config['marginUsed']:.5f}")
                    openTrades=relay.GetOpenTrades(symbol=pair)

                # Replaceent order, start at bottom

                if not AlreadyBought(relay,pair,ticker['Ask'],Config['pipStep']+Config['BuyPips']+Config['marginPips']+Config['unitPips']+Config['VolatilityPips']+ticker['Spread']) or isClustering:
                    # Get the margin used
                    Config['marginUsed']=GetMarginUsed(relay,pair)

                    lotSize=ClusterStyle(openTrades,relay,pair,Config)
                    newPos=Config['marginUsed']+(float(relay.Markets[pair]['marginRate'])*lotSize)

                    if Config['marginLimit']<0 or (Config['marginLimit']>0 and newPos<Config['marginLimit']):
                        details=relay.GetOrderDetails(OrderID=id)[-1]
                        price=float(details['price'])
                        result=SendOrder(relay,Action="buy",Units=-lotSize)
                        oid=GetOrderID(result)
                        if oid!=None:
                            relay.JRLog.Write(f"{GetForexSession():4} Short - {clusterStr}Replacement {oid} Buy @{price:7.5f} -> {lotSize}")
                            Config['BuyPips']=ticker['Spread']
                            openTrades=relay.GetOpenTrades(symbol=pair)
    # No trades to scan
    elif Config['First']==True and (Config['marginLimit']<0 or Config['marginLimit']>0):
        highestPrice=ticker['Ask']

        lotSize=LowestLotSize(openTrades,relay,pair,Config)
        buy=ticker['Ask']
        result=SendOrder(relay,Action="buy",Units=-lotSize)
        oid=GetOrderID(result)
        if oid!=None:
            Config['BuyPips']=ticker['Spread']
            Config['First']=False
            relay.JRLog.Write(f"{GetForexSession():4} Short - {oid} Buy @{buy:7.5f} -> {lotSize}")
            openTrades=relay.GetOpenTrades(symbol=pair)

    # Next buy price minus pip step

    buy=round(highestPrice+Config['pipStep']+Config['BuyPips']+Config['marginPips']+Config['unitPips']+Config['VolatilityPips']+ticker['Spread'],5)
    lotSize=LowestLotSize(openTrades,relay,pair,Config)

    if ticker['Ask']>buy:
        if not AlreadyBought(relay,pair,ticker['Ask'],Config['pipStep']+Config['BuyPips']+Config['marginPips']+Config['unitPips']+Config['VolatilityPips']+ticker['Spread']):
            lotSize=ClusterStyle(openTrades,relay,pair,Config)
            newPos=Config['marginUsed']+(float(relay.Markets[pair]['marginRate'])*lotSize)

            if Config['marginLimit']<0 or (Config['marginLimit']>0 and newPos<Config['marginLimit']):
                details=relay.GetOrderDetails(OrderID=id)[-1]
                price=float(details['price'])
                result=SendOrder(relay,Action="buy",Units=-lotSize)
                oid=GetOrderID(result)
                if oid!=None:
                    relay.JRLog.Write(f"{GetForexSession():4} Short - {oid} Buy @{price:7.5f} -> {lotSize}")
                    openTrades=relay.GetOpenTrades(symbol=pair)
                    Config['BuyPips']=ticker['Spread']

    return Config

###
### Main code base.
###

Config=ReadConfig(sys.argv[1])

# Clear the config argument, otherwise the Relay method will try to process it.
sys.argv.remove(sys.argv[1])

while True:
    # pairAccount: EUR/USD.CherryBlossom, dictionaries must have unique keys.
    for pairAccount in Config:
        startTime=time.time()

        # Get the trading pair
        pair=Config[pairAccount]['Asset']

        # Initialize this asset
        relay=JRR.JackrabbitRelay(framework='oanda',exchange='oanda',account=Config[pairAccount]['Account'],asset=pair)

        # Get balance
        # OANDA has a 50% margin call rule, so cut balance in half for what is actually useable.
        Config[pairAccount]['balance']=relay.GetBalance()

        # Get the list of open trades
        openTrades=relay.GetOpenTrades(symbol=pair)

        # Get the ticker

        ticker=relay.GetTicker(symbol=pair)
        Config[pairAccount]=LoadTickerData(Config[pairAccount],ticker)

        # Set up Price element

        if Config[pairAccount]['Direction'].lower()=='long':
            Config[pairAccount]['Price']=ticker['Bid']
        elif Config[pairAccount]['Direction'].lower()=='short':
            Config[pairAccount]['Price']=ticker['Ask']

        # Iniial values fon configuration file

        # Get the margin used
        Config[pairAccount]['marginUsed']=GetMarginUsed(relay,pair)

        # Figure out margin limit and take into account the current NAV

        if '%' in Config[pairAccount]['MarginLimit']:
            Config[pairAccount]['marginLimit']=(float(Config[pairAccount]['MarginLimit'].replace('%',''))/100)*Config[pairAccount]['balance']
        else:
            Config[pairAccount]['marginLimit']=float(Config[pairAccount]['MarginLimit'])

        if Config[pairAccount]['marginLimit']>Config[pairAccount]['balance']:
            Config[pairAccount]['marginLimit']=Config[pairAccount]['balance']

        # If margin limit greater the 0, calculate the net asset value (NAV) and substract it from the allowable limit.
        # This provides a true assessment of what is really available for consumption. The goal with this approach is to
        # prevent a margin call by keeping the bot with the allowable true amount available for purhasing.
        # A marginit limit of 0 means buying is disabled.

        if Config[pairAccount]['marginLimit']>0:
            nav=0
            for trade in openTrades:
                nav+=round(float(trade['unrealizedPL']),5)
            # nav will be expressed as a negative value
            # marginLimit-(nav+marginUsed)=marginFree
            # Margin limit will be less than balance, this ensures that when trading multiple pairs, the account will be stable,
            # providing the marginit limit total of ALL pairs remains below 100% usage. Not perfect, but at least better then
            # nothing.
            Config[pairAccount]['marginLimit']-=round(abs(nav)+Config[pairAccount]['marginUsed'],5)
            if Config[pairAccount]['marginLimit']<0:
                Config[pairAccount]['marginLimit']=0

        # Set margin pips
        Config[pairAccount]['marginPips']=Config[pairAccount]['marginUsed']*0.0001

        # Get the highest lot size and convert to pips
        Config[pairAccount]['obDirection']=GetOrderBookDirection(relay,Config[pairAccount])
        Config[pairAccount]['unitPips']=HighestLotSize(openTrades,relay,pair,Config[pairAccount])*0.0001

        # The range of actual profit and distance from other orders. spread is added
        # automatically.

        Config[pairAccount]['pipStep']=CalculatePipProfits(relay,Config[pairAccount])

        # Use a 100 step basis to optimize profit based on rolling market history.
        # The larger the distance between high and low, the greater the potential is for profit.

        if 'MaxBA' in Config[pairAccount]['TickerData'][-1] and 'MinBA' in Config[pairAccount]['TickerData'][-1]:
            mh=Config[pairAccount]['TickerData'][-1]['MaxBA']
            ml=Config[pairAccount]['TickerData'][-1]['MinBA']
            Config[pairAccount]['pipStep']+=round((mh-ml)/100,5)

        # Calculate volatility pips

        Config[pairAccount]['VolatilityPips']=CalculateVolatilityPips(relay,Config[pairAccount])

        # We need to track the spread at purchase to add into the selling limit. We want to be sure we get
        # the above profits for each trade.

        if 'BuyPips' not in Config[pairAccount] or Config[pairAccount]['BuyPips']==0:
            Config[pairAccount]['BuyPips']=ticker['Spread']

        # Trade based on direction

        if Config[pairAccount]['Direction'].lower()=='long':
            Config[pairAccount]=ManageLongs(relay,pair,Config[pairAccount],ticker)
        elif Config[pairAccount]['Direction'].lower()=='short':
            Config[pairAccount]=ManageShorts(relay,pair,Config[pairAccount],ticker)

        # Memory purge

        Config[pairAccount]['TickerData']=None

        gc.collect()

        # End of the loop and this asset

        endTime=time.time()-startTime
        print(f"{endTime:7.4f} {Config[pairAccount]['Direction'][0]} {GetForexSession():4} {Config[pairAccount]['Account']:20} {pair:8} {len(openTrades):3.0f} {Config[pairAccount]['BuyPips']:.5f} {Config[pairAccount]['pipStep']:.5f} {Config[pairAccount]['marginPips']:.5f} {Config[pairAccount]['unitPips']:.5f} {Config[pairAccount]['VolatilityPips']:.5f} {ticker['Spread']:.5f} {Config[pairAccount]['balance']:9.5f} {Config[pairAccount]['marginUsed']:9.5f}/{Config[pairAccount]['marginLimit']:9.5f}")

        interceptor.SafeExit()
        JRRsupport.ElasticSleep(1)

    print('')

###
### End of program
###
