#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import json

import JRRsupport

MimicData='/home/JackrabbitRelay2/Data/Mimic/'

###
### Main code base.
###

if len(sys.argv)<4:
    print("A Mimic account, a currency and a value are required.")
    sys.exit(1)

account=sys.argv[1]
acn=f'{MimicData}{account}.wallet'
if not os.path.exists(acn):
    print('Please verify wallet name and case')
    sys.exit(1)

base=sys.argv[2].upper()
amount=float(sys.argv[3])

walletLock=JRRsupport.Locker(acn,ID=acn)
walletLock.Lock()

Wallet=json.loads(JRRsupport.ReadFile(acn).strip().split('\n')[0])

Wallet['Wallet'][base]=round(amount,8)
Wallet.pop(base,None)

JRRsupport.WriteFile(acn,json.dumps(Wallet)+'\n')
walletLock.Unlock()

print(f"{base} in {account} set to {amount:.8f}")
