#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import json

import JRRsupport

MimicData='/home/JackrabbitRelay2/Data/Mimic/'

###
### Main code base.
###

if len(sys.argv)<2:
    print("A Mimic account and an asset are required.")
    sys.exit(1)

account=sys.argv[1]
asset=sys.argv[2]
pair=asset.replace('/','').replace(':','')

lines=JRRsupport.ReadFile(f'{MimicData}{account}.history').strip().split('\n')

cnr=0

for line in lines:
    if line=='':
        continue

    try:
        data=json.loads(line)
    except:
        print("Line damaged:")
        print(f"  {line}")
        sys.exit(1)

    if asset!=data['Asset']:
        continue

    base,quote=asset.split('/')
    if ':' in asset:
        quote=asset.split(':')[1]
        if '-' in quote:
            quote=quote.split('-')[0]

    dt=data['DateTime']
    act=data['Action'].upper()[0]
    bw=float(data[base])
    qw=float(data[quote])
    a=float(data['Amount'])
    p=float(data['Price'])
    f=float(data['Fee'])

    if act=='B':
        cnr-=abs(p*a)
    elif act=='S':
        cnr+=abs(p*a)

    print(f"{dt} {act} {bw:14.8f} {qw:14.8f} {a:14.8f} {p:.8f} {f:.8f} {cnr:14.8f}")

