#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import json

import JRRsupport

MimicData='/home/JackrabbitRelay2/Data/Mimic/'

###
### Main code base.
###

if len(sys.argv)<2:
    print("A Mimic account is required.")
    sys.exit(1)

account=sys.argv[1]
acn=f'{MimicData}{account}.history'
if not os.path.exists(acn):
    print('Please verify wallet name and case')
    sys.exit(1)

lines=JRRsupport.ReadFile(acn).strip().split('\n')

fees={}
cnr={}
Wallet={}

for line in lines:
    if line=='':
        continue

    try:
        data=json.loads(line)
    except:
        print("Line damaged:")
        print(f"  {line}")
        sys.exit(1)

    asset=data['Asset']
    base,quote=asset.split('/')
    if ':' in asset:
        quote=asset.split(':')[1]
        if '-' in quote:
            quote=quote.split('-')[0]

    dt=data['DateTime']
    act=data['Action'].upper()[0]
    bw=float(data[base])
    qw=float(data[quote])
    a=float(data['Amount'])
    p=float(data['Price'])
    f=float(data['Fee'])

    if data['Asset'] not in cnr:
        cnr[data['Asset']]=0

    if data['Asset'] not in Wallet:
        Wallet[data['Asset']]=[]

    if data['Asset'] not in fees:
        fees[data['Asset']]=0

    if act=='B':
        if bw!=0:
            cnr[data['Asset']]-=abs(p*a)
        else:
            cnr[data['Asset']]+=abs(p*a)
    elif act=='S':
        cnr[data['Asset']]+=abs(p*a)

    fees[data['Asset']]+=f

    str=f"{dt} {act} {bw:14.8f} {qw:14.8f} {a:14.8f} {p:.8f} {f:.8f} {cnr[data['Asset']]:14.8f}"
    Wallet[data['Asset']].append(str)

for pair in sorted(Wallet.keys()):
    if len(sys.argv)>2 and sys.argv[2]!=pair:
        continue

    print(f"{pair}: {fees[pair]:.8f} paid in fees")
    for l in Wallet[pair]:
        print(f"   {l}")
    print()
