#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import datetime
import json
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as ps

import JRRsupport

chartDir='/home/JackrabbitRelay2/Data/Charts/'
MimicData='/home/JackrabbitRelay2/Data/Mimic/'

StableCoinUSD=['USDT','USDC','BUSD','UST','DAI','FRAX','TUSD', \
               'USDP','LUSD','USDN','HUSD','FEI','TRIBE','RSR','OUSD','XSGD', \
               'GUSD','USDX','SUSD','EURS','CUSD','USD']


###
### Main code base.
###

if len(sys.argv)<4:
    print("You MUST specify either (I)mage or (H)tml for output type")
    print("A Mimic account and an asset are required.")
    sys.exit(1)

ih=sys.argv[1].lower()
if ih!='i' and ih!='h':
    print("You MUST specify either (I)mage or (H)tml for output type")
    sys.exit(1)

exchange='mimic'
account=sys.argv[2]
asset=sys.argv[3]

acn=f'{MimicData}{account}.history'
if not os.path.exists(acn):
    print('Please verify wallet name and case')
    sys.exit(1)

lines=JRRsupport.ReadFile(acn).strip().split('\n')

xps=[]
bExposure=[]
qExposure=[]
cnr=[]

xnr=0
for line in lines:
    if line=='':
        continue

    try:
        data=json.loads(line)
    except:
        print("Line damaged:")
        print(f"  {line}")
        sys.exit(1)

    pair=data['Asset']
    base,quote=asset.split('/')
    if ':' in asset:
        quote=asset.split(':')[1]
        if '-' in quote:
            quote=quote.split('-')[0]

    if pair!=asset:
        continue

    dt=data['DateTime']
    act=data['Action'].upper()[0]
    bw=float(data[base])
    qw=float(data[quote])
    a=float(data['Amount'])
    p=float(data['Price'])
    f=float(data['Fee'])

    if act=='B':
        if bw!=0:
            xnr-=abs(p*a)
        else:
            xnr+=abs(p*a)
    elif act=='S':
        xnr+=abs(p*a)

    xps.append(dt)
    if base not in StableCoinUSD:
        bExposure.append(bw*p)
    else:
        bExposure.append(bw)

    if quote not in StableCoinUSD:
        qExposure.append(qw*p)
    else:
        qExposure.append(qw)
    cnr.append(xnr)

# Make the chart
pair=sys.argv[3].replace('/','').split(':')[0]
if ih=='h':
    fn=chartDir+f'Exposure.{exchange}.{account}.{pair}.html'
else:
    fn=chartDir+f'Exposure.{exchange}.{account}.{pair}.png'

ts=f"Mimic Exposure: {account} - {asset}"

fig1=ps.make_subplots(specs=[[{"secondary_y":False}]])

fig1.add_trace(go.Scatter(x=xps,y=cnr,name='Exposure',marker_color="#0000ff"),secondary_y=False)
fig1.add_trace(go.Scatter(x=xps,y=bExposure,name='Base'),secondary_y=False)
fig1.add_trace(go.Scatter(x=xps,y=qExposure,name='Quote'),secondary_y=False)

fig1.update_yaxes(title_text='Exposure Curve',secondary_y=False)
fig1.update_layout(title={"text":ts,"x":0.5,"xanchor":"center","yanchor":"top"},template='plotly_white')

if ih=='h':
    fig1.add_layout_image(dict(
        source='https://rapmd.net/RAPMDlogo.png',
        xref='paper',yref='paper',
        xanchor='center',yanchor='middle',
        x=0.5,y=0.5,
        sizex=1,sizey=1,
        opacity=0.1
    ))
else:
    fig1.add_layout_image(dict(
        source='file:///var/www/vhosts/rapmd.net/httpdocs/RAPMDlogo.png',
        xref='paper',yref='paper',
        xanchor='center',yanchor='middle',
        x=0.5,y=0.5,
        sizex=1,sizey=1,
        opacity=0.1
    ))

if ih=='h':
    fig1.write_html(fn)
else:
    fig1.write_image(fn,width=1920,height=1024)
