#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json
import time

import JRRsupport
import JackrabbitRelay as JRR

NewOrder='{"Recipe":"BuyEveryMinute Conditional","Action":"Buy","Exchange":"mimic","Market":"spot","Account":"phemexPublic","Asset":"XRP/USDT","Base":"-1","OrderType":"Market","Conditional":"Yes","Direction":"Short","SellAction":"Sell","TakeProfit":"1%","StopLoss":"10%" }'

###
### Main driver
###

def main():
    relay=JRR.JackrabbitRelay(payload=NewOrder,NoIdentityVerification=True)
    relay.Order['Identity']=relay.Active['Identity']

    while True:
        # Feed the new order to Relay
        result=relay.SendWebhook(relay.Order)
        oid=relay.GetOrderID(result)
        if oid!=None:
            bal=relay.GetBalance(Base=relay.Order['Asset'].split('/')[0])
            detail=relay.GetOrderDetails(id=oid,symbol=relay.Order['Asset'])
            print(oid,round(detail['Price'],8),round(bal,8))
        JRRsupport.ElasticSleep(60)

if __name__ == '__main__':
    main()
