#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time
import random

import JRRsupport

if __name__=='__main__':
    interceptor=JRRsupport.SignalInterceptor(IsMain=True)
else:
    interceptor=JRRsupport.SignalInterceptor(IsMain=False)

def RandoSleeper():
    t=random.randint(1,20)
    print(f"{os.getppid()}/{os.getpid()}: {interceptor.WhoAmI()} sleeping {t} seconds")
    time.sleep(t)

def main():
    print(f"Parent: {os.getpid()}, {interceptor.AnyTriggered()}")
    RandoSleeper()

    for i in range(100):
        interceptor.StartProcess(RandoSleeper)
        while interceptor.GetChildren()>10:
            l=interceptor.GetChildren()
            print(f"{i}/{l} {interceptor.AnyTriggered()}")
            if l==0:
                break
            time.sleep(1)

    while True:
        l=interceptor.GetChildren()
        print(l,interceptor.AnyTriggered())
        if l==0:
            break
        time.sleep(1)

###
### Main driver
###

if __name__=='__main__':
    main()

###
### End
###

