#!/bin/python3

import sys
import json

def main():
    if len(sys.argv) != 2:
        print("Usage: python script.py <key_name>")
        sys.exit(1)

    key_name = sys.argv[1]

    for line in sys.stdin:
        try:
            data = json.loads(line.strip())
            print(json.dumps(data,indent=2))
        except json.JSONDecodeError as e:
            print(f"Invalid JSON: {e}")

if __name__ == "__main__":
    main()
