#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time
import random

import JRRsupport

if __name__=='__main__':
    interceptor=JRRsupport.SignalInterceptor(IsMain=True)
else:
    interceptor=JRRsupport.SignalInterceptor(IsMain=False)

def RandoSleeper():
    t=random.randint(1,20)
    print(f"{os.getppid()}/{os.getpid()}: sleeping {t} seconds")
    JRRsupport.ElasticSleep(t)

###
### Main driver
###

def main():
    print(f"Parent: {os.getpid()}")

    while True:
        interceptor.StartProcess(RandoSleeper)
        while interceptor.GetChildren()>10:
            JRRsupport.ElasticSleep(1)

if __name__=='__main__':
    main()

###
### End
###

