#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time

import JRRsupport

fw1=JRRsupport.Locker("LockerTest")
fw2=JRRsupport.Locker("LockerTest")

print(fw1.Lock())
print(fw2.Lock())
print(fw1.Unlock())
