#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import json

import JackrabbitRelay as JRR

def Help(args,argslen):
    print("An exchange and an account must be provided.")
    sys.exit(1)

relay=JRR.JackrabbitRelay(Usage=Help)

exchangeName=relay.GetExchange()
account=relay.GetAccount()

for cur in relay.Markets:
    print(relay.Markets[cur])
