#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time
import json

import JRRsupport
import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() < 3:
    print("An exchange and a (sub)account must be provided.")
    sys.exit(1)

fn=relay.DataDirectory+'/'+relay.Exchange+'.'+relay.Account+'.MaxAssets'
tList=JRRsupport.TimedList("MaxAssets",fn,Timeout=300)
dataDB=tList.read()

for asset in dataDB:
    item=json.loads(dataDB[asset])
    e=(item['Expire']-time.time())/86400
    print(f"{asset:20} {e:.8f}")
