#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time

import JRRsupport

tv=str(time.time())

fw1=JRRsupport.Locker("Locker.Mempory."+tv,Timeout=60)

data=str(time.time())

print(fw1.Put(3600,'Alpha'))
print(fw1.Get())

print(fw1.Put(3600,'Beta'))
print(fw1.Get())

print(fw1.Put(3600,'Delta'))
print(fw1.Get())

print(fw1.Put(3600,'Gamma'))
print(fw1.Get())

print(fw1.Put(3600,data))
print(fw1.Get())

print(fw1.Erase())
print(fw1.Get())
