#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import gc
import json
import time

import JRRsupport
import JackrabbitRelay as JRR

NewOrder='{"Action":"Buy","Exchange":"mimic","Market":"spot","Account":"phemexPublic","Asset":"XRP/USDT","Base":"1.56657287","OrderType":"Market","Conditional":"Yes","Direction":"Long","SellAction":"Sell","TakeProfit":"1%","StopLoss":"10%" }'

interceptor=JRRsupport.SignalInterceptor()

def ConditionalMaker(*args):
    relay=JRR.JackrabbitRelay(payload=NewOrder,NoIdentityVerification=True)
    relay.Order['Identity']=relay.Active['Identity']

    oid='17113826983214236'
    od=relay.GetOrderDetails(id=oid,symbol='XRP/USDT')
    relay.Order['Response']=od
    relay.Order['Details']=od

    relay.MakeConditionalOrder(oid,relay.Order)

###
### Main driver
###

def main():
    amt=1.56657287
    start=1854-(667*amt)
    end=3
    while start>=end:
        interceptor.StartProcess(ConditionalMaker)

        while interceptor.GetChildren()>0:
            time.sleep(1)

        start-=amt
        print(start)

        relay=None
        od=None
        gc.collect()

if __name__ == '__main__':
    main()

