#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

###
### Main code base. Place order on exchange
###

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 5:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    asset=relay.GetAsset()
    amount=relay.GetArgs(4)
    ticket=int(relay.GetArgs(5))
else:
    print("An exchange, (sub)account, asset, units, and ticket must be provided.")
    sys.exit(1)

result=relay.PlaceOrder(pair=asset,orderType="market",action="sell",amount=amount,ticket=ticket,price=1)
print(result)
