#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 3:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    asset=relay.GetAsset()
else:
    print("An exchange, (sub)account, and an asset must be provided.")
    sys.exit(1)

markets=relay.Markets

oo=relay.GetOpenTrades(symbol=asset)

tpnl=0
for o in oo:
    iu=int(o['currentUnits'])
    price=float(o['price'])
    upl=float(o['unrealizedPL'])
    fin=float(o['financing'])
    tpnl+=upl+fin
    if iu>=0:
        side='Long'
    else:
        side='Shrt'
    print(f"{o['openTime']} {o['instrument']:10} {o['id']:7} {side:4} {iu:16.5f} {price:16.5f} {upl:16.5f} {fin:16.5f}")
print("\n",round(tpnl,5),len(oo))
