#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json
import datetime

import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 3:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    asset=relay.GetAsset()
else:
    print("An exchange, (sub)account, and an asset must be provided.")
    sys.exit(1)

markets=relay.Markets

oo=relay.GetOpenTrades(symbol=asset)

tpnl=0
for o in oo:
    # find trade open time
    parts=o['openTime'].split('.')
    dsS=f"{parts[0]}.{parts[1][:6]}Z"
    dt=datetime.datetime.strptime(dsS,'%Y-%m-%dT%H:%M:%S.%fZ')
    epoch=dt.timestamp()

    iu=int(o['currentUnits'])
    price=float(o['price'])
    upl=float(o['unrealizedPL'])
    fin=float(o['financing'])
    tpnl+=upl+fin
    if iu>=0:
        side='L'
    else:
        side='S'
    print(f"{o['openTime']} {o['id']:>7} {side} {abs(iu):4.0f} {price:10.5f} {upl:9.5f} {fin:9.5f}")
print("\n",round(tpnl,5),len(oo))
