#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 5:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    pair=relay.GetAsset()
    mkt=relay.GetArgs(4)
    oid=relay.GetArgs(5)
else:
    print("An exchange, (sub)account, an asset, a market, and an order ID must be provided.")
    sys.exit(1)

markets=relay.Markets

if relay.Framework=='oanda':
    oo=relay.GetOrderDetails(OrderID=oid)
    if oo!=None:
        for o in oo:
            print(f'{o}\n')
    else:
        print("Order is still pending or is incomplete")
elif relay.Framework=='ccxt':
    oo=relay.GetOrderDetails(id=oid,symbol=pair)
    print(oo)
    if oo==None or oo==[]:
        res=relay.FindLedgerID(ID=oid,Exchange=exchangeName,Account=account,Asset=pair,Market=mkt)
        print(res)
else:
    oo=relay.GetOrderDetails(id=oid,symbol=pair)
    print(json.dumps(oo,indent=2))
