#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 3:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    pair=relay.GetAsset()
    oid=relay.GetArgs(4)
else:
    print("An exchange, (sub)account, and an order ID must be provided.")
    sys.exit(1)

markets=relay.Markets

if relay.Framework=='oanda':
    oo=relay.GetOrderDetails(OrderID=oid)
    if oo!=None:
        for o in oo:
            print(f'{o}\n')
    else:
        print("Order is still pending or is incomplete")
elif relay.Framework=='ccxt':
    oo=relay.GetOrderDetails(id=oid,symbol=pair)
    print(json.dumps(oo,indent=2))
