#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 3:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    oid=relay.GetAsset()
else:
    print("An exchange, (sub)account, and an order ID must be provided.")
    sys.exit(1)

markets=relay.Markets

if relay.Framework=='oanda':
    oo=relay.GetOrderDetails(OrderID=oid)
    for o in oo:
        print(f'{o}\n')
elif relay.Framework=='ccxt':
    oo=relay.GetOrderDetails(id=oid)

