#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

###
### Main code base. Place order on exchange
###

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 4:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    asset=relay.GetAsset()
    amount=relay.GetArgs(4)
else:
    print("An exchange, (sub)account, an asset, and an amount must be provided.")
    sys.exit(1)

markets=relay.GetMarkets()

ticker=relay.GetTicker(symbol=asset)
if relay.GetFramework()=='ccxt':
    bid=ticker['ask']
elif relay.GetFramework()=='oanda':
    bid=ticker['Ask']

result=relay.PlaceOrder(pair=asset,orderType="market",action="buy",amount=amount,price=bid,ReduceOnly=False,LedgerNote="Dry Run")
print(result)

print("")

result=relay.PlaceOrder(pair=asset,orderType="market",action="sell",amount="all",price=bid,ReduceOnly=False,LedgerNote="Dry Run")
print(result)
