#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os

import JackrabbitRelay as JRR

###
### Main code base. Place order on exchange
###

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 2:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
else:
    print("An exchange and a (sub)account must be provided.")
    sys.exit(1)

# Already loaded from login

markets=relay.Markets
timeframes=relay.Timeframes
print(timeframes)

