#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

###
### Main code base. Place order on exchange
###

relay=JRR.JackrabbitRelay(None,sys.stdin.read())

print(json.dumps(relay.Order,indent=2),'\n')

print("Varable ",relay.Exchange)
print("Funcrion",relay.GetExchange())
print("List    ",relay.ExchangeList)
print("GetList ",relay.GetExchangeList())
print("Next    ",relay.GetExchangeNext())
print("After   ",relay.GetExchangeAfterNext())
