#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import signal

import JRRsupport

interceptor=JRRsupport.SignalInterceptor()

a=0
b=0

while True:
    interceptor.Critical(True)
    print(interceptor.critical,interceptor.triggered)
    print(a,b)

    a+=1
    interceptor.SafeExit()
    b+=1
    print("Critical Sleep")
    JRRsupport.ElasticSleep(10)
    interceptor.Critical(False)

    print("Non-critical Sleep")
    JRRsupport.ElasticSleep(10)
