#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
import os

###
### Main code base. Place order on exchange
###

nl2sp=False
if len(sys.argv)>1:
    nl2sp=True

data=sys.stdin.read()

if nl2sp:
    data=data.replace('\n\n',' ').replace('\n',' ')

print(data)


