#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import time

import JRRsupport

inp=sys.stdin.read()

print("1st:",JRRsupport.StopHTMLtags(inp))
print(JRRsupport.StopHTMLtags(inp,full=True))

