#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json
import time

import JRRsupport

s=time.time()
lines=sys.stdin.readlines()
e=time.time()-s
print(f"Reading data took {e} seconds over {len(lines)} lines")

tList=JRRsupport.TimedList("Timed List Test","timedList.test",Timeout=300)

s=time.time()
tList.purge()
e=time.time()-s
print(f"Purge took {e} seconds over {len(lines)} lines")

st=time.time()
for line in lines:
    line=line.strip()

    dataTV=json.loads(line)
    key=dataTV['Recipe'].replace(" ","")+dataTV['Exchange']+dataTV['Asset']+dataTV['TCycles']+dataTV['TBuys']
#    s=time.time()
    results=tList.update(key,line,300)
#    e=time.time()-s
#    if results['Status']!='ErrorLimit':
#        print(f"{e:4.8f} {results['Status']:10} {results['Payload']}")
#    else:
#        print(f"Max Limit, purging...")
#        tList.purge()

et=time.time()-st
print(f"Took {et} seconds to process {len(lines)} lines")



