#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json
import time

import JRRsupport

s=time.time()
buffer=JRRsupport.ReadFile("testData")
JRRsupport.WriteFile("opData",buffer)
e=time.time()-s
print(f"Copy file took {e} seconds for {len(buffer)} bytes")

s=time.time()
lines=JRRsupport.ReadFile("opData").split('\n')
for i in range(9000):
    lines=lines[1:]
e=time.time()-s
print(f"ReadFile/parse/list delete took {e} seconds over {len(lines)} lines")

s=time.time()
fh=open("opData","r")
lines=fh.readlines()
fh.close()
for i in range(9000):
    lines=lines[1:]
e=time.time()-s
print(f"bulk readlines/delete took {e} seconds over {len(lines)} lines")

s=time.time()
fh=open("opData","r")
lines=[]
for line in fh.readlines():
    lines.append(line.strip())
fh.close()
for i in range(9000):
    lines=lines[1:]
e=time.time()-s
print(f"1by1 readline()/delete took {e} seconds over {len(lines)} lines")

s=time.time()
dList=JRRsupport.DList()
fh=open("opData","r")
lines=fh.readlines()
for line in lines:
    line=line.strip()
    if line!=None and line!='':
        dList.insert(line)
fh.close()
for i in range(9000):
    dList.delete(dList.GetHead().GetData())
e=time.time()-s
print(f"dList(dup filter)/1by1 took {e} seconds over {dList.Length()} lines")

s=time.time()
dList=JRRsupport.DList()
lines=JRRsupport.ReadFile("opData").split('\n')
for line in lines:
    line=line.strip()
    if line!=None and line!='':
        dList.insert(line)
for i in range(9000):
    dList.delete(dList.GetHead().GetData())
e=time.time()-s
print(f"dList(dup filter)/ReadFile took {e} seconds over {dList.Length()} lines")
