#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay Technical Analysis example

# 2021-2025 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import math
import json
import datetime
import time

import JackrabbitRelay as JRR
import JRRtechnical as jrTA

def main():
    ohlcv=[]

    ta=jrTA.TechnicalAnalysis('kraken','MAIN','ADA/USD','1m',197)

    # Build my own candles. No live candles. A candle is returned only after it
    # is closed.

    c=0
    while c<10:
        ohlcv=ta.MakeOHLCV(seconds=60)
        print(ohlcv)
        c+=1

if __name__=='__main__':
    main()
