#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay Technical Analysis example

# 2021-2025 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import math
import json
import datetime
import time

import JackrabbitRelay as JRR
import JRRtechnical as jrTA

def main():
    ohlcv=[]

    ta=jrTA.TechnicalAnalysis('kraken','MAIN','ADA/USD','1m',197)

    # Live display of candles
    c=0
    while c<10:
        # Automaricalling adds to rolling window
        ta.UpdateOHLCV()
        ta.Display(-1)
        c+=1
        time.sleep(60) # for 1 minute candles

if __name__=='__main__':
    main()
