#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import ccxt

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

Bal2LotsHeader='Balance2Lots '+JRRconfig.Version

###
### Determine number of lots based on balance on exchange
###

def main():
    hasUSD=False
    hasBase=False
    hasQuote=False

# Get exchange and asset

    if len(sys.argv) > 4:
        exchangeName=sys.argv[1].lower()
        account=sys.argv[2]
        pair=sys.argv[3].upper()
        pct=float(sys.argv[4])
    else:
        print("An exchange, a (sub)account, an asset, and a percentage boundary must be provided.")
        sys.exit(1)

    if len(sys.argv) > 5:
        maxSteps=float(sys.argv[5])
    else:
        maxSteps=100

# Load the API/Secret information

    keys=JRRsupport.ReadConfig(exchangeName,account)
    if keys==[]:
        print("Reading Config","No API/Secret found for "+exchangeName+", (sub)account: "+account)
        sys.exit(1)

    CurrentKey=(os.getpid()%len(keys))
    Active=keys[CurrentKey]
    if "Retry" in Active:
        RetryLimit=int(Active['Retry'])
    else:
        RetryLimit=10

    keys=JRRsupport.ReadConfig(exchangeName,account)

    exchange=JRRapi.ExchangeLogin(exchangeName,Active,Notify=False)

    exchange.verbose=False

    markets=JRRapi.GetMarkets(exchange,pair,RetryLimit,Notify=False)

    quote=exchange.markets[pair]['quote']
    if quote not in JRRconfig.StableCoinUSD:
        hasQuote=True
    else:
        hasQuote=False

# Get exchange required minimums

    minimum,mincost=JRRapi.GetMinimum(exchange,pair,hasQuote,False,RetryLimit)

# Convert balance to number of steps and lots

    balance = exchange.fetch_balance()
    bal=float(balance['total'][quote])
    steps=maxSteps/pct
    priceStep=bal/steps
    Lots=priceStep/mincost

    if Lots<1:
        Lots=1

    print(f"{Lots:.8f}")

if __name__ == '__main__':
    main()
