#!/bin/bash

# Crontab entry ( without hash mark #)
# @reboot ( /home/JackrabbitRelay/Base/RelayLauncher & ) > /dev/null 2>&1
# echo "BalAnce" | tr "[:upper:]" "[:lower:]"

# /home/Equilibrium/Equilibrium.spot kucoin MAIN crv/usdt 1 100 AUTO

# $1 Exchange
# $2 Account
# $3 Pair
# $4 Boundary Percentage, Take Profit, Deviation
# $5 Buy Lots
# $6 Sell Lots
# $7 Paper trading indicator

BaseDir="/home/Equilibrium"

cd $BaseDir

while true ; do
    $BaseDir/Equilibrium.spot $@
    if [ $? -eq 2 ] ; then
        exit
    fi
    sleep 60
done
