#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Equilibrium
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
import os

if len(sys.argv) > 3:
    exchangeName=sys.argv[1].lower()
    account=sys.argv[2]
    pair=sys.argv[3].upper()

    fn=exchangeName+'.'+account+'.'+pair.replace("-","").replace("/","")
    fnStop=fn+'.stop'
    fh=open(fnStop,'w')
    fh.write("Stop!\n")
    fh.close()

