#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# Mimic
# 2024-03-25 16:15:21.152559   47120 17110487079419736: Prft long, 0.64438, 1.56739812: 0.63800000 -> 0.644400/0.01003135
# Oanda
# 2024-02-15 01:29:28.047577 1152604 78276 -> 78271 Prft short, 61.0: 0.64905 -> 0.647920/0.06890, 2:45:07.902341

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import datetime
import json
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as ps

import JRRsupport

chartDir='/home/JackrabbitRelay2/Data/Charts/'

###
### Main code base.
###

if len(sys.argv)<3:
    print("You MUST specify either (I)mage or (H)tml for output type")
    print("An Oliver Twist log file is required")
    sys.exit(1)

ih=sys.argv[1].lower()
if ih!='i' and ih!='h':
    print("You MUST specify either (I)mage or (H)tml for output type")
    sys.exit(1)

entry={}

xps=[]
equity=[]
pnl=0

data=sys.argv[2].split('.')
exchange=data[1]
account=data[2]
pair=data[3]

if 'mimic' in sys.argv[2].lower():
    asset=data[4]
    pair=data[4]
else:
    asset=data[3][:3]+'/'+data[3][3:]

lines=JRRsupport.ReadFile(sys.argv[2]).strip().split('\n')

for line in lines:
    if line=='' or ('Prft' not in line and 'Loss' not in line and 'Rduc' not in line):
        continue

    data=line.split(' ')

    dt=data[0]+' '+data[1]

    pdata=line.split('/')[1].strip().split(',')[0]

    if 'Prft' in line:
        pnl+=float(pdata)
    if 'Loss' in line or 'Rduc' in line:
        pnl-=float(pdata)

    xps.append(dt)
    equity.append(pnl)

# Make the chart

if ih=='h':
    fn=chartDir+f'Equity.{exchange}.{account}.{pair}.html'
else:
    fn=chartDir+f'Equity.{exchange}.{account}.{pair}.png'

ts=f"OliverTwist Equity Curve: {account} - {asset}"

fig1=ps.make_subplots(specs=[[{"secondary_y":False}]])

fig1.add_trace(go.Scatter(x=xps,y=equity,name='Equity',marker_color="#0000ff"),secondary_y=False)

if os.path.exists('/home/JackrabbitRelay2/Data/logo.png'):
    if ih=='h':
        fig1.add_layout_image(dict(
            source='/logo.png',
            xref='paper',yref='paper',
            xanchor='center',yanchor='middle',
            x=0.5,y=0.5,
            sizex=1,sizey=1,
            opacity=0.1
        ))
    else:
        fig1.add_layout_image(dict(
            source='file:///home/JackrabbitRelay2/Data/logo.png',
            xref='paper',yref='paper',
            xanchor='center',yanchor='middle',
            x=0.5,y=0.5,
            sizex=1,sizey=1,
            opacity=0.1
        ))
fig1.update_yaxes(title_text='Equity Curve',secondary_y=False)
fig1.update_layout(title={"text":ts,"x":0.5,"xanchor":"center","yanchor":"top"},template='plotly_white')

if ih=='h':
    fig1.write_html(fn)
else:
    fig1.write_image(fn,width=1920,height=1024)
