#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time

import JRRsupport

###
### Main code base.
###

if len(sys.argv)<2:
    print("At least one Oliver Twwist log file is required.")
    sys.exit(1)

summary=False
if len(sys.argv)>2:
    summary=True

tt=0
sl=0
rs=0
day={}
for i in range(1,len(sys.argv)):
    if 'oanda' in sys.argv[i]:
        perc=4
    else:
        perc=8

    lines=JRRsupport.ReadFile(sys.argv[i]).strip().split('\n')

    # Running Sum
    pnl=0

    for line in lines:
        if line=='' or ('Prft' not in line and 'Loss' not in line):
            continue

        data=line.split(' ')

        dmy=data[0].split(' ')[0].split('-')
        date=dmy[0]+'-'+dmy[1] # +'-'+dmy[2]

        pdata=line.split('/')[1].strip().split(',')[0]

        if 'Prft' in line:
            pnl=float(pdata)
        if 'Loss' in line:
            pnl=-float(pdata)
        rs+=pnl

        if date in day:
            day[date]+=pnl
        else:
            day[date]=pnl

        if 'Prft' in line or 'Loss' in line:
            tt+=1
        if 'Loss' in line:
            sl+=1

    for d in sorted(day.keys()):
        exac=sys.argv[i].split('.')
        print(f"{d} {exac[2]:<10} {exac[3]:<20} {round(day[d],4):14.{perc}f}")

print()

# Trades/Month
if len(day.keys())>0:
    tpm=int(tt/len(day.keys()))
    atm=round(rs/tt,perc)
    apm=round(atm*tpm,perc)

    print(f"Total Profits/StopLosses/Trades: {round(rs,perc):.{perc}f}/{sl}/{tt}")
    print(f"Average/Trade:        {atm:.{perc}f}")
    print(f"Average Trades/Month: {tpm:.0f}")
    print(f"Average Profit/Month: {apm:.{perc}f}")
