#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json
import time

import apiKucoin

API=os.environ["API"]
SECRET=os.environ["SECRET"]
PASS=os.environ["PASS"]

sb=False
if len(sys.argv)>1:
    sb=True

exchange=apiKucoin.Broker(API=API,SECRET=SECRET,Passphrase=PASS,Sandbox=sb)

#print(json.dumps(exchange.apiGetV1SubUser(),indent=2),'\n')

# FAILS
#print(json.dumps(exchange.apiGetV2SubUser(pageSize=1),indent=2),'\n')

#print(json.dumps(exchange.apiGetV1Accounts(accountType='main'),indent=2),'\n')
#print(json.dumps(exchange.apiGetV1Accounts(),indent=2),'\n')
#print(json.dumps(exchange.apiGetV1Accounts(accountType='margin'),indent=2),'\n')

#id=exchange.apiGetV1Accounts()[-1]['id']
#print(json.dumps(exchange.apiGetV1AccountsID(acctID=id),indent=2),'\n')

#print(json.dumps(exchange.apiGetV1AccountsLedgers(endAt=time.time()),indent=2),'\n')

# FAILS
#print(json.dumps(exchange.apiGetV1UserInfo(),indent=2),'\n')

#print(json.dumps(exchange.apiPostV1SubUser(subName="JackrabbitTest2",password="fuzzy3wuzzy7fluffy2pants",remarks="Test"),indent=2),'\n')

#sn=exchange.apiGetV1SubUser()[-1]['subName']
#print(json.dumps(exchange.apiPostV1SubApiKey(subName=sn,passphrase="fuzzy3wuzzy7fluffy2pants",remark="TestAPI"),indent=2),'\n')
#print(json.dumps(exchange.apiPostV1SubApiKey(subName=sn,passphrase="fuzzy3wuzzy7fluffy2pants",remark="TestAPI2",permission="Trade"),indent=2),'\n')

#apk=exchange.apiGetV1SubApiKey(subName=sn)[0]['apiKey']
#print(json.dumps(exchange.apiPostV1SubApiKeyUpdate(subName=sn,apiKey=apk,passphrase="fuzzy3wuzzy7fluffy2pants",ipWhitelist="127.0.0.17"),indent=2),'\n')
#print(json.dumps(exchange.apiPostV1SubApiKeyUpdate(subName=sn,apiKey=apk,passphrase="fuzzy3wuzzy7fluffy2pants",ipWhitelist="127.0.0.37"),indent=2),'\n')

# FAILS
#print(json.dumps(exchange.apiDeleteV1SubApiKey(subName=sn,apiKey=apk,passphrase="fuzzy3wuzzy7fluffy2pants"),indent=2),'\n')

#print(json.dumps(exchange.apiGetV1SubApiKey(subName=sn),indent=2),'\n')

#for i in [ 'main','trade','margin' ]:
#    coinList=exchange.apiGetV1Accounts(accountType=i)
#    for coin in coinList:
#        print(f"{'MAIN':20} {i:20} {coin['currency']}")
#acctList=exchange.apiGetV2SubUser(pageSize=100)['items']
#for acct in acctList:
#    uid=acct['userId']
#    if uid==None:
#        continue
#    sn=acct['subName']
#    for i in [ 'main','trade','margin' ]:
#        acct=i+'Accounts'
#        coinList=exchange.apiGetV1SubAccounts(subUserId=uid)[acct]
#        for coin in coinList:
#            print(f"{sn:20} {i:20} {coin['currency']}")
