#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
from socketserver import ForkingMixIn
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime
import subprocess
import json

import JRRconfig

LogDirectory="/home/JackrabbitRelay2/Logs"
BaseDirectory='/home/JackrabbitRelay2/Base'

# Write pid in port file

def WritePID(port):
    fn=BaseDirectory+'/'+str(port)+'.pid'
    f = open(fn, "w")
    f.write(str(os.getpid()))
    f.close()

# Write log entry

def WriteLog(addr,msg):
    time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

    s=f'{time} {addr:16} {msg}\n'

    fh=open(LogDirectory+'/JackrabbitRelay.log','a')
    fh.write(s)
    fh.close()

# Process the trade and send it to the correct transactor

def ProcessSingleTrade(addr,trades):
    res=""

    exchange=None
    fn=None
    ts=BaseDirectory+'/PlaceOrder.'

    if "Exchange" in trades and "Market" in trades:
        exchange=trades['Exchange'].lower()
        market=trades['Market'].lower()
        fn=ts+exchange+'.'+market
        if not os.path.exists(fn):
            exchange=trades['Exchange'].lower()
            fn=ts+exchange
    elif "Exchange" in trades:
        exchange=trades['Exchange'].lower()
        fn=ts+exchange

    if os.path.exists(fn):
        transactor=[ fn ]
        subp=subprocess.Popen(transactor,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        data=json.dumps(trades)

        subp.stdin.write(data.encode())
        res=subp.communicate()[0]
        code=subp.poll()
    else:
        WriteLog(addr,"Transactor not found for exchange and/or market: "+fn)

    return res

def ProcessTrade(addr,payload):
    res=""

    # This is where we need to break down the payload to see if it is a single JSON
    # or multiple JSON messages

    try:
        trades=json.loads(payload,strict=False)
    except:
        trades=None
        WriteLog(addr,"Damaged payload:"+str(payload))

    if trades!=None:
        if type(trades)==dict:
            res=ProcessSingleTrade(addr,trades)
        else:
            for trade in trades:
                res+=str(ProcessSingleTrade(addr,trade))

    if type(res)!=bytes:
        res=res.encode('utf-8')
    return res

def ProcessStatistatorium(addr,path):
    ws=JRRconfig.BaseDirectory+'/Statistatorium'
    idf=JRRconfig.ConfigDirectory+'/Identity.cfg'

    if os.path.exists(ws) and os.path.exists(idf):
        transactor= [ ws ]
        subp=subprocess.Popen(transactor,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)

        # Web server request is pushed in as STDIN

        subp.stdin.write(path.encode())
        res=subp.communicate()[0]
    else:
        res=JRRconfig.NOhtml
        WriteLog(addr,f"Transactor not found.")

    return res

def CheckIPaddress(addr):
    fn=JRRconfig.ConfigDirectory+'/IPList.cfg'
    if os.path.exists(fn):
        cf=open(fn,'rt+')
        for line in cf.readlines():
            line=line.strip()
            if len(line)>0 and line[0]!='#':
                if line==addr:
                    cf.close()
                    return True
        cf.close()
        return False

    # if file doesn't exist, revert to previous functionality
    return True

class Handler(BaseHTTPRequestHandler):

    def log_message(self,format,*args):
        addr=self.client_address[0]
        time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

        s=f'{time} {addr:16} {args}\n'

        fh=open(LogDirectory+'/JackrabbitRelay.log','a')
        fh.write(s)
        fh.close()

    def do_GET(self):
        addr=self.client_address[0]

        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(bytes('\r\n'.encode()))

        res=ProcessStatistatorium(addr,self.path)

        if res!=None:
            if type(res)!=bytes:
                res=res.encode('utf-8')
            self.wfile.write(res)
        return res

    def do_POST(self):
        res=None
        # Send the client a success response
        addr=self.client_address[0]

        if CheckIPaddress(str(addr)):
            self.send_response(200)
            self.end_headers()
            self.wfile.write(bytes('\r\n'.encode()))

            # Get the length of the post data
            content_len = int(self.headers.get_all('content-length', 0)[0])

            # Read the post data

            payload = self.rfile.read(content_len)

            # Process Payload

            res=ProcessTrade(addr,payload)

            if res!=None:
                if type(res)!=bytes:
                    res=res.encode('utf-8')
                self.wfile.write(res)
        return res

class ForkingSimpleServer(ForkingMixIn, HTTPServer):
    pass

def main():
    if len(sys.argv) > 1:
        port = int(sys.argv[1])
    else:
        print("Port number not given, exiting...")
        sys.exit(2)

    WritePID(port)
    WriteLog(JRRconfig.Version,"Jackrabbit Relay")

    try:
        server = ForkingSimpleServer(('', port), Handler)
    except OSError as err:
        x=str(err)
        if x.find('Address already in use')>-1:
            print('Another program is using this port: '+str(port))
        else:
            print(x)
        WriteLog(JRRconfig.Version,x)
        sys.exit(1)

    addr, port = server.server_address

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Terminated")

if __name__ == '__main__':
    main()


