#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Locker
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# For (un)locking

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Lock", "Expire":"300" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Unlock" }

# For memory reference

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Get" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Put", "Expire":"300","DataStore":"Blah" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Erase" }

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
from datetime import datetime
import socket
import select
import json

import JRRsupport

Version="0.0.0.1.0"
BaseDirectory='/home/JackrabbitRelay2/Base'
ConfigDirectory='/home/JackrabbitRelay2/Config'
LogDirectory="/home/JackrabbitRelay2/Logs"

# Required global for the process to work

Locker={}
dataStore={}

# Write pid in port file

def WritePID(port):
    fn=BaseDirectory+'/'+str(port)+'.pid'
    f = open(fn, "w")
    f.write(str(os.getpid()))
    f.close()

# Write log entry

def WriteLog(addr,msg):
    time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

    s=f'{time} {addr:16} {msg}\n'

    fh=open(LogDirectory+'/JackrabbitLocker.log','a')
    fh.write(s)
    fh.close()

def jsonStatus(str,Tag=None,Data=None):
    res={}
    res['Status']=str

    if Tag!=None and Data!=None:
        res[Tag]=Data

    return json.dumps(res)+'\n'

def ProcessPayload(data):
    global Locker

    try:
        dataDB=json.loads(data)
    except: # damaged payload
        return jsonStatus("BadPayload")
    else: # Find the lock

        # FileName and Action are required. For memory fetches, FileName is memory ID.

        if 'FileName' not in dataDB \
        or 'Action' not in dataDB:
            return jsonStatus("BadPayload")

        # Valid actions:
        #    Lock        Complete
        #    Unlock      Complete
        #    Get
        #    Put
        #    Erase

        # What are we doing. FileName also doubles as memory ID
        FileName=dataDB['FileName']
        action=dataDB['Action'].lower()

        # Link this entry to the connected socket
        if action=='lock':
            # New request
            if FileName not in Locker:
                dataLock={}
                dataLock['ID']=dataDB['ID']
                dataLock['Expire']=time.time()+float(dataDB['Expire'])
                Locker[FileName]=dataLock
                return jsonStatus("Locked")
            # Lock has expired, now unlocked
            elif time.time()>Locker[FileName]['Expire']:
                Locker[FileName]['ID']=dataDB['ID']
                Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
                return jsonStatus("Locked")
            else:
                if Locker[FileName]['ID']==dataDB['ID']:
                    Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
                    return jsonStatus("Locked")
                else:
                    return jsonStatus("Failure")
        # Get memory reference
        elif action=='get':
            if FileName not in Locker:
                return jsonStatus("NotFound")
            # Verify owner and unlock/Erase memory
            elif Locker[FileName]['ID']==dataDB['ID']:
                return jsonStatus("Done",Tag="DataStore",Data=Locker[FileName]['DataStore'])
            # Not the rightful owner
            else:
                return jsonStatus("NotOwner")
        elif action=='put':
            # New memory object
            if FileName not in Locker:
                dStore={}
                dStore['ID']=dataDB['ID']
                dStore['Expire']=time.time()+float(dataDB['Expire'])
                dStore['DataStore']=dataDB['DataStore']
                Locker[FileName]=dStore
                return jsonStatus("Done")
            # Existing memory object, verify owner
            elif Locker[FileName]['ID']==dataDB['ID']:
                Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
                Locker[FileName]['DataStore']=dataDB['DataStore']
                return jsonStatus("Done")
            # Not the rightful owner
            else:
                return jsonStatus("NotOwner")
        # Unlock/Erase request
        elif action=='unlock':
            # Just pass through unlock
            if FileName not in Locker:
                return jsonStatus("Unlocked")
            # Verify owner and unlock
            elif Locker[FileName]['ID']==dataDB['ID']:
                Locker[FileName]['Expire']=0
                return jsonStatus("Unlocked")
            else:
                return jsonStatus("Failure")
        # Unlock/Erase request
        elif action=='erase':
            # Just pass through unlock/erase
            if FileName not in Locker:
                return jsonStatus("Done")
            # Verify owner and erase memory
            elif Locker[FileName]['ID']==dataDB['ID']:
                Locker[FileName]['Expire']=0
                Locker[FileName]['DataStore']=None
                return jsonStatus("Done")
            else:
                return jsonStatus("Failure")
            # Wrong key
        else:
            return jsonStatus("BadAction")

###
### Main Driver
###

def main():
    global Locker
    global dataStore

    port=37373

    WritePID(port)

    try:
        lockerSocket=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        lockerSocket.setblocking(0)
        lockerSocket.bind(('', port))
        lockerSocket.listen(1024)
    except OSError as err:
        x=str(err)
        if x.find('Address already in use')>-1:
            x='Another program is using this port: '+str(port)
        WriteLog(Version,x)
        sys.exit(1)

    # Track incoming connections

    inputs=[lockerSocket]

    # Response queue connected to each client

    queue={}

    while True:
        infds,outfds,errfds=select.select(inputs, inputs, [], 30)

        if len(infds)!=0:
            for fds in infds:
                if fds is lockerSocket:
                    clientsock,clientaddr=fds.accept()
                    clientsock.setblocking(0)
                    if clientsock not in inputs:
                        inputs.append(clientsock)
                    dataStore[clientsock]=''
                else:
                    data=None
                    try:
                        data=fds.recv(1024)
                    except:
                        # Sleep based upon server load
                        JRRsupport.ElasticSleep(0)

                    # No data received, close connection, clean up and sleep

                    if not data:
                        if fds in inputs:
                            inputs.remove(fds)
                        if fds in queue:
                            queue.pop(fds,None)
                        fds.close()
                        now=time.time()
                        for k in list(Locker):
                            if now>Locker[k]['Expire']:
                                Locker.pop(k,None)
                    else:
                        # Collect the entire line.
                        data=data.decode()
                        dataStore[fds]+=data
                        if data[-1]=='\n':
                            queue[fds]=ProcessPayload(dataStore[fds])

        # Send response and close connection

        if len(outfds)!=0:
            for fds in outfds:
                if fds in queue:
                    try:
                        fds.sendall(queue[fds].encode())
                    except:
                        if fds in inputs:
                            inputs.remove(fds)
                        fds.close()
                    queue.pop(fds,None)

if __name__ == '__main__':
    main()
