#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
from socketserver import ForkingMixIn
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime
import subprocess
import json

import JRRsupport

Version="0.0.0.1.470"
BaseDirectory='/home/JackrabbitRelay2/Base'
ConfigDirectory='/home/JackrabbitRelay2/Config'
LogDirectory="/home/JackrabbitRelay2/Logs"
NOhtml='<html><title>NO!</title><body style="background-color:#ffff00;display:flex;weight:100vw;height:100vh;align-items:center;justify-content:center"><h1 style="color:#ff0000;font-weight:1000;font-size:10rem">NO!</h1></body></html>'

# Set up signal interceptor

interceptor=JRRsupport.SignalInterceptor()

# Filter end of line and hard spaces

def pFilter(s):
    d=s.replace("\\n","").replace("\\t","").replace("\\r","")

    for c in '\t\r\n \u00A0':
        d=d.replace(c,'')

    return(d)

# Write pid in port file

def WritePID(port):
    fn=BaseDirectory+'/'+str(port)+'.pid'
    f = open(fn, "w")
    f.write(str(os.getpid()))
    f.close()

# Write log entry

def WriteLog(addr,msg):
    time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

    s=f'{time} {addr:16} {msg}\n'

    fh=open(LogDirectory+'/JackrabbitRelay.log','a')
    fh.write(s)
    fh.close()

# Process the trade and send it to the correct transactor

def ProcessSingleTrade(addr,trades):
    res=""
    idf=ConfigDirectory+'/Identity.cfg'

    if not os.path.exists(idf):
        WriteLog(addr,"Identity not found")
        return res

    # handle exchange list

    if ',' in trades['Exchange']:
        exchange=trades['Exchange'].split(',')[0].lower().strip()
    else:
        exchange=trades['Exchange'].lower().strip()

    fn=None
    ts=BaseDirectory+'/PlaceOrder.'

    if "Exchange" in trades and "Market" in trades:
        market=trades['Market'].lower().strip()
        fn=ts+exchange+'.'+market
        # if market not part of place order program, revert to exchange only
        if not os.path.exists(fn):
            fn=ts+exchange
    elif "Exchange" in trades:
        fn=ts+exchange
    else:
        WriteLog(addr,"Transactor not found for exchange and/or market: "+fn)
        return res

    if os.path.exists(fn):
        transactor=[ fn ]
        subp=subprocess.Popen(transactor,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        data=json.dumps(trades)

        subp.stdin.write(data.encode())
        res=subp.communicate()[0]
        code=subp.poll()
    else:
        WriteLog(addr,"Transactor not found for exchange and/or market: "+fn)

    return res

def ProcessTrade(addr,payload):
    res=""

    # This is where we need to break down the payload to see if it is a single JSON
    # or multiple JSON messages

    try:
        trades=json.loads(pFilter(payload),strict=False)
    except:
        trades=None
        WriteLog(addr,"Damaged payload: "+str(payload))
        return res

    if trades!=None:
        if type(trades) is dict:
            res=ProcessSingleTrade(addr,trades)
        elif type(trades) is list:
            for trade in trades:
                res+=str(ProcessSingleTrade(addr,trade))
        else:
            trades=None
            t=type(payload)
            p=str(payload)
            WriteLog(addr,f"Unrecognized payload type: {t}/{p}")
            return res

    if type(res)is not bytes:
        res=res.encode('utf-8')
    return res

def ProcessPageRead(addr,path):
    return NOhtml

def CheckIPaddress(addr):
    fn=ConfigDirectory+'/IPList.cfg'
    if os.path.exists(fn):
        cf=open(fn,'rt')
        for line in cf.readlines():
            line=line.strip()
            if len(line)>0 and line[0]!='#':
                if line==addr:
                    cf.close()
                    return True
        cf.close()
        return False

    # V1 allowed trades without ip list verification. V2 will NOT any trades without the ip
    # list file. if file doesn't exist, don't accept trade. This is going to be a real pain in
    # the ass with load balancers, but overall security must be at the forfront.

    return False

class Handler(BaseHTTPRequestHandler):
    BaseHTTPRequestHandler.server_version='JackrabbitRelay/'+Version
    BaseHTTPRequestHandler.sys_version=''

    def log_message(self,format,*args):
        addr=self.client_address[0]
        time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

        s=f'{time} {addr:16} {args}\n'

        fh=open(LogDirectory+'/JackrabbitRelay.log','a')
        fh.write(s)
        fh.close()

    # Handle URL dispatcher here.

    def do_GET(self):
        addr=self.client_address[0]

        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(bytes('\r\n'.encode()))

        # Gives a big red NO to everything

        res=ProcessPageRead(addr,self.path)

        if res!=None:
            if type(res)is not bytes:
                res=res.encode('utf-8')
            self.wfile.write(res)
        return res

    # Handle trades here

    def do_POST(self):
        res=None
        # Send the client a success response
        addr=self.client_address[0]

        if CheckIPaddress(str(addr)):
            self.send_response(200)
            self.end_headers()
            self.wfile.write(bytes('\r\n'.encode()))

            # Get the length of the post data
            content_len = int(self.headers.get_all('content-length', 0)[0])

            # Read the post data

            payload = self.rfile.read(content_len)

            # Process Payload

            res=ProcessTrade(addr,payload.decode())

            if res!=None:
                if type(res)!=bytes:
                    res=res.encode('utf-8')
                self.wfile.write(res)
        return res

class ForkingSimpleServer(ForkingMixIn, HTTPServer):
    pass

def main():
    if len(sys.argv) > 1:
        port = int(sys.argv[1])
    else:
        print("Port number not given, exiting...")
        sys.exit(2)

    # Sanity check: Identity.cfg REQUIRED!
    if not os.path.exists(ConfigDirectory+'/Identity.cfg'):
        print("Identity.cfg is now REQUIRED, but not found.")
        sys.exit(2)

    # Sanity check: IPList.cfg REQUIRED!
    if not os.path.exists(ConfigDirectory+'/IPList.cfg'):
        print("IPList.cfg is now REQUIRED, but not found.")
        sys.exit(2)

    WritePID(port)
    WriteLog(Version,"Jackrabbit Relay")

    try:
        server = ForkingSimpleServer(('', port), Handler)
    except OSError as err:
        x=str(err)
        if x.find('Address already in use')>-1:
            print('Another program is using this port: '+str(port))
        else:
            print(x)
        WriteLog(Version,x)
        sys.exit(1)

    addr, port = server.server_address

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Terminated")

if __name__ == '__main__':
    main()
