#!/bin/bash

# Crontab entry ( without has mark #
# @reboot ( /home/JackrabbitRelay2/Base/RelayLauncher & ) > /dev/null 2>&1

BaseDir="/home/JackrabbitRelay2/Base"

Port=$1

if [ -z $Port ] ; then
    echo A port to use must be given.
    exit 1
fi

cd $BaseDir

while true ; do
    $BaseDir/JackrabbitRelay $Port
    sleep 180
done


