#!/bin/bash

# Crontab entry ( without has mark #
# @reboot ( /home/JackrabbitRelay2/Base/RelayLauncher & ) > /dev/null 2>&1

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

e=`ps xa | egrep -c "JackrabbitDLM$"`
if [[ $e -gt 0 ]] ; then
    echo JackrabbitDLM loaded
    exit 0
fi

BaseDir="/home/JackrabbitRelay2/Base"

cd $BaseDir

while true ; do
    $BaseDir/JackrabbitLocker
    sleep 60
done


