#!/bin/bash

# Crontab entry ( without has mark #
# @reboot ( /home/JackrabbitRelay2/Base/RelayLauncher & ) > /dev/null 2>&1

BaseDir="/home/JackrabbitRelay2/Base"

cd $BaseDir

while true ; do
    $BaseDir/JackrabbitLocker
    sleep 180
done


