#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Equilibrium
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import time
import json

import JRRsupport

def main():
    if len(sys.argv) > 1:
        fn=sys.argv[1]
    else:
        print("Coin list file required.")
        sys.exit(0)

    coins={}

    fw=JRRsupport.FileWatch(fn)
    fw.Lock()

    try:
        if os.path.exists(fn):
            cf=open(fn,'rt+')
            buffer=cf.read()
            cf.close()
            coins=json.loads(buffer)

        for c in coins:
            t=(time.time()-coins[c])
            d=t/86400
            print(f"{c:12} {d:4.6f}")
    except:
        pass

    fw.Unlock()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("Terminated")

