#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import json

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

###
### Main code base.
###

def main():
    try:
        payload=JRRsupport.pFilter(sys.stdin.read())
        depth=payload.count('/')
        path=JRRconfig.ChartsDirectory+'/'+payload[1:].replace('/','.')+'.html'

        if os.path.exists(path):
            f=open(path,'r')
            fc=f.read()
            f.close()
            print(fc)
        else:
            el=[]
            cfiles=os.listdir(JRRconfig.ChartsDirectory)

            for i in cfiles:
                f='/'+i
                l=len(payload)
                p=f[:l].replace('.','/')
                if payload!='/':
                    if p==payload:
                        x=f[l+1:].split('.')[0]
                        if x not in el:
                            el.append(x)
                else:
                    if p==payload:
                        x=f[l:].split('.')[0]
                        if x not in el:
                            el.append(x)

            if len(el)>0:
                el.sort()

                print("<html><head><title>Jackrabbit Statistatorium</title></head>")
                print("<body><h1><center>Jackrabbit Statistatorium</center></h1>")
                print('<p><h2><center><a href="/">Top</a>')
                p=payload[1:].find('/')
                if payload!='/' and p>-1:
                    print(f'<a href="{payload[:p+1]}">{payload[1:p+1]}</a>')
                print('</center></h2><p><center>')
                if depth==2:
                    print(f'<a href="{payload}/Ledger">Ledger</a><p>')

                for i in el:
                    if 'Ledger' in i:
                        continue
                    if payload!='/':
                        print(f'<a href="{payload}/{i}">{i}</a>')
                        if depth==2:
                            print('<br>')
                    else:
                        print(f'<a href="/{i}">{i}</a>')
                print("</center></body></html>")
            else:
                print(JRRconfig.NOhtml)
    except:
        print(JRRconfig.NOhtml)

if __name__ == '__main__':
    try:
        main()
    except:
        print(JRRconfig.NOhtml)
