#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay/Base/Library')
import os
import ccxt

import JRRconfig
import JRRlog
import JRRapi
import JRRsupport

AnalyzeHeader='AnalyzeAsset '+JRRconfig.Version

###
### Main code base. Place order on exchange
###

def main():
    JRRlog.WriteLog(AnalyzeHeader)

    hasUSD=False
    hasBase=False
    hasQuote=False

# Get exchange and asset

    if len(sys.argv) > 3:
        exchangeName=sys.argv[1].lower()
        account=sys.argv[2]
        pair=sys.argv[3].upper()
    else:
        print("An exchange, a (sub)account, and an asset must be provided.")
        sys.exit(1)

    JRRlog.WriteLog('|- Exchange: '+exchangeName)
    JRRlog.WriteLog('|- Account: '+account)
    JRRlog.WriteLog('|- Asset: '+pair)

# Load the API/Secret information

    if account.upper()!='NONE':
        keys=JRRsupport.ReadConfig(exchangeName,account)
        if keys==[]:
            JRRlog.ErrorLog("Reading Config","No API/Secret found for "+exchangeName+", (sub)account: "+account)
        else:
            JRRlog.WriteLog("API/Secret loaded for "+exchangeName+", (sub)account: "+account)

        CurrentKey=(os.getpid()%len(keys))
        Active=keys[CurrentKey]

        if len(keys)>1:
            JRRlog.WriteLog("|- Using rotating key set "+str(CurrentKey+1))

        if exchangeName in ccxt.exchanges:
            try:
                exchange=getattr(ccxt,exchangeName)( \
                    { 'apiKey': Active['API'],'secret': Active['SECRET'] })
            except Exception as e:
                JRRlog.ErrorLog("Connecting to exchange",e)
        else:
            if exchangeName=="ftxus":
                try:
                    exchange=ccxt.ftx({ 'hostname': 'ftx.us', \
                        'apiKey': Active['API'],'secret': Active['SECRET'] })
                except Exception as e:
                    JRRlog.ErrorLog("Connecting to exchange",e)
            else:
                JRRlog.ErrorLog(exchangeName,"Exchange not supported")
    else:
        JRRlog.WriteLog("NO API/Secret loaded, using public API")

        if exchangeName in ccxt.exchanges:
            try:
                exchange=getattr(ccxt,exchangeName)()
            except Exception as e:
                JRRlog.ErrorLog("Connecting to exchange",e)
        else:
            if exchangeName=="ftxus":
                try:
                    exchange=ccxt.ftx({ 'hostname': 'ftx.us' })
                except Exception as e:
                    JRRlog.ErrorLog("Connecting to exchange",e)
            else:
                JRRlog.ErrorLog(exchangeName,"Exchange not supported")

# Special settings

    if "createMarketBuyOrderRequiresPrice" in exchange.options:
        JRRlog.ErrorLog(exchangeName,"Exchange not supported")

    # Set FTX and FTX US subaccount. Not sure if I need to reset API/secret yet.

    if account.upper()!='NONE':
        if exchangeName=="ftx" and Active['Account']!='MAIN':
            exchange.headers['FTX-SUBACCOUNT']=Active['Account']
            exchange.apiKey=Active['API']
            exchange.secret=Active['SECRET']
        else:
            if exchangeName=="ftxus" and Active['Account']!='MAIN':
                exchange.headers['FTXUS-SUBACCOUNT']=Active['Account']
                exchange.apiKey=Active['API']
                exchange.secret=Active['SECRET']

        if "RateLimit" in Active:
            exchange.enableRateLimit=True
            exchange.rateLimit=int(Active['RateLimit'])
            JRRlog.WriteLog("|- Rate limit set to "+str(Active['RateLimit'])+' ms')
        else:
            exchange.enableRateLimit=False

        if "Retry" in Active:
            RetryLimit=int(Active['Retry'])
            JRRlog.WriteLog("|- API Retry limit set to "+str(RetryLimit)+' times')
        else:
            RetryLimit=1000
    else:
        RetryLimit=3
        RateLimit=1000

    exchange.verbose=False

    markets=JRRapi.GetMarkets(exchange,RetryLimit)
    JRRlog.WriteLog("Markets loaded")

# Sanity check

    if pair[0]=='.' or pair.find(".d")>-1:
        JRRlog.ErrorLog(ExchangeName,pair+" is not tradable on this exchange")

    if pair not in exchange.markets:
        JRRlog.ErrorLog(exchangeName,pair+" is not traded on this exchange")

    if 'active' in exchange.markets[pair]:
        if exchange.markets[pair]['active']==False:
            JRRlog.ErrorLog(exchangeName,pair+" is not active on this exchange")

    quote=exchange.markets[pair]['quote']
    if quote not in JRRconfig.StableCoinUSD:
        hasQuote=True
    else:
        hasQuote=False

# Get exchange required minimums

    minimum,mincost=JRRapi.GetMinimum(exchange,pair,hasQuote,True,RetryLimit)

# Final amount to be used by system.

    JRRlog.WriteLog("Exchange required minimum:  "+f"{minimum:.6f}")
    JRRlog.WriteLog("Exchange required min cost: "+f"{mincost:.6f}")
    JRRlog.ElapsedTime(JRRconfig.StartTime)

if __name__ == '__main__':
    main()
