#!/usr/bin/env python

import random

letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-={}[]<>,.;:/~"
llen=len(letters)

def main():
    l=random.randrange(1024,2047)

    pw=""
    oc=""

    for i in range(l):
        done=False
        while not done:
            for z in range(random.randrange(73,237)):
                c=random.randrange(llen)
            if pw=="" or (len(pw)>0 and letters[c]!=oc):
                done=True
        oc=letters[c]

        pw+=oc

    print('{ "Identity":"'+pw+'" }')

if __name__ == "__main__":
    main()

