#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitRelay2/Base/Library')
import os
import json

import JackrabbitRelay as JRR

def Help(args,argslen):
    print("An exchange and an account must be provided.")
    sys.exit(1)

relay=JRR.JackrabbitRelay(Usage=Help)

exchangeName=relay.GetExchange()
account=relay.GetAccount()

# Already loaded from login

markets=relay.Markets

TradingView={}
if relay.GetFramework()=='oanda':
    for cur in markets:
        p=markets[cur]
        tv=p['displayName'].replace('/','').replace('_','')
        ns=p['displayName']
        TradingView[tv]=ns
elif relay.GetFramework()=='ccxt':
    for cur in markets:
        p=markets[cur]
        if 'type' in p and p['type'].lower()!='spot':
            tv=p['id'].replace('/','').replace('-','').replace(':','')+':'+p['type'].lower()
        else:
            tv=p['id'].replace('/','').replace('-','').replace(':','')
        ns=p['symbol']
        TradingView[tv]=ns

fn=relay.DataDirectory+'/'+exchangeName+'.'+account+'.symbolmap'
fh=open(fn,'w')
fh.write(json.dumps(TradingView)+"\n")
fh.close()

print(f'{exchangeName}/{account} symbol map file written')
